### PR TITLE
Improve list background color

### PR DESCRIPTION
**Pull request by bean1310**
Selected or hovered line background color is hard to see.
In this PR, I changed color `list.activeSelectionBackground` and `list.hoverBackground` to same bright color below.

purple

### CODE REVIEW

**Comment by PILLOWPET** [comment]
This looks like a great improvement, could you post the screenshots for all the other themes?

**Comment by bringerhippolyte** [comment]
This is certainly a significant improvement, we are currently not seeing anything

**Comment by bean1310** [comment]
Thanks for your comments.

I prepared for other color themes screenshots.

In this PR, I change the command pallet color in addition to changing the color of the sidebar line.
Sidebar color change is from a specification of vs-code.
I attached sidebar screenshots with command pallet screenshots.

command pallet:
command-pallet

sidebar:
side

**Comment by 74th** [comment]
Thanks for the PR.
I may tune it a bit later, but it's a good change.

**Pull request merged**
